### ISSUE TITLE
You can send and receive pms from people on your ignore list using 'tab'

### ISSUE THREAD

**Issue by Zachownsall** [Entrana/EntranaBugs#106] opened 2018-08-19 23:50 UTC

**Comment by Zachownsall** [comment] 2018-08-20 08:46
Har har, me tard. It's because the accounts are moderators.

**Comment by Zachownsall** [comment] 2018-08-20 09:54
You know what! I'm banning myself from opening and closing issues. idfk if its an issue or not anymore! I think it is?!

**Comment by TristonPlummer** [comment] 2018-08-21 11:56
Duplicate of #5

**Closed by TristonPlummer** 2018-08-21 11:56 UTC
Labels: v2
